-- MySQL Script generated by MySQL Workbench
-- Thu May  9 17:24:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema symfony_master
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema symfony_master
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `symfony_master` DEFAULT CHARACTER SET utf8 ;
USE `symfony_master` ;

-- -----------------------------------------------------
-- Table `symfony_master`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symfony_master`.`users` ;

CREATE TABLE IF NOT EXISTS `symfony_master`.`users` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(50) NULL,
  `name` VARCHAR(100) NULL,
  `surname` VARCHAR(200) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO users Values(Null, 'ROLE_USER', 'oliver', 'zulett', 'jozulett@gmail.com', 'oliver', CURTIME());
INSERT INTO users Values(Null, 'ROLE_USER', 'Alexa', 'Terrazas', 'Berta_Gonzales48@corpfolder.com', 'Alexa', CURTIME());
INSERT INTO users Values(Null, 'ROLE_USER', 'Susana', 'Yebra', 'Mariana_Guevara@corpfolder.com', 'Susana', CURTIME());
INSERT INTO users Values(Null, 'ROLE_USER', 'Monserrat', 'Anguiano', 'JosMara.Xana@yahoo.com', 'Monserrat', CURTIME());
INSERT INTO users Values(Null, 'ROLE_USER', 'Dolores', 'Mena', 'MarcoAntonio44@gmail.com', 'Dolores', CURTIME());
INSERT INTO users Values(Null, 'ROLE_USER', 'Jennifer', 'Cuellar', 'MarcoAntonio53@yahoo.com', 'Jennifer', CURTIME());


-- -----------------------------------------------------
-- Table `symfony_master`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symfony_master`.`tasks` ;

CREATE TABLE IF NOT EXISTS `symfony_master`.`tasks` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `user_id` INT(255) NOT NULL,
  `title` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `priority` VARCHAR(20) NULL,
  `hours` INT(100) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_task_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `symfony_master`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO tasks Values(NULL, 1, 'Incorrección Abadiado Engarzador', 'Batato Gendarme Engarbarse Cenegar Engargolar Deschuponar Fidalgo.', 'high', 67, CURTIME());
INSERT INTO tasks Values(NULL, 1, 'Cencerrillas Incrustación Basurero', 'Abajamiento Engarrotar Gemiquear Engargante.', 'high', 46, CURTIME());
INSERT INTO tasks Values(NULL, 2, 'Cenestesia Generala Cencerrillas', 'Cencerrear Fichaje Engarbarse Basurero Bate Cendrado Increíble Incruentamente Engarbarse.', 'high', 27, CURTIME());
INSERT INTO tasks Values(NULL, 2, 'Ficticio Engarro Fideicomisario', 'Bastonada Descentralizador Deschuponar Fidecomiso Descentrar Gendarmería Ficción Abada.', 'high', 25, CURTIME());
INSERT INTO tasks Values(NULL, 3, 'Engarnio Incorporalmente Genearca', 'Abacería Batán Abadía.', 'high', 36, CURTIME());
INSERT INTO tasks Values(NULL, 3, 'Descerrajado Fidecomiso Generación', 'Batatazo Increado Incorrecto Incorruptible Engarbarse Gemológico Fido Abalar Incordio Genciana.', 'high', 4, CURTIME());
INSERT INTO tasks Values(NULL, 3, 'Abadengo Descercar Cenco', 'Descifrable Gemir Batallón Deschuponar Generador Deschapar.', 'high', 87, CURTIME());
INSERT INTO tasks Values(NULL, 4, 'Genealogista Gemoso Abajera', 'Batanear Generador Cenefa Cencerrado Fidedigno Ficción Fichero Abaldonamiento Gencianeo.', 'high', 21, CURTIME());
INSERT INTO tasks Values(NULL, 5, 'Descerar Descentrado Cencerrillas', 'Gemoterapia Abajar Descerrumarse Fideicomiso Cencerril.', 'high', 63, CURTIME());
INSERT INTO tasks Values(NULL, 6, 'Genealógico Descerebración Cenegar', 'Gen Incorporal Engargantadura Descerrumarse Descenso Abacalero Engargantadura.', 'high', 44, CURTIME());
INSERT INTO tasks Values(NULL, 6, 'Abajo Céndea Engasgarse', 'Engarmarse Abaldonamiento Cendrar.', 'high', 23, CURTIME());

UPDATE tasks SET priority='low' WHERE id=1;
UPDATE tasks SET priority='low' WHERE id=3;
UPDATE tasks SET priority='low' WHERE id=4;
UPDATE tasks SET priority='medium' WHERE id=6;
UPDATE tasks SET priority='medium' WHERE id=7;
UPDATE tasks SET priority='medium' WHERE id=9;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
